Sprint 9
StRaiGT/java-filmorate pull request #1
Opened 2022-10-31 20:00 UTC by StRaiGT

2022-11-01 10:19 UTC, AnastasiyaFomkina requested changes

2022-11-01 10:19 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getReleaseDate().isBefore(LocalDate.of(1895, 12, 28))) {
`LocalDate.of(1895, 12, 28)` - можно сделать константой

2022-11-01 10:19 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +import org.springframework.web.bind.annotation.*;
_Саморазвитие_
В коммерческой разработке не принято использовать `wildcard` в импортах.
Вот отличная [статья](https://struchkov.dev/blog/using-wildcard-imports-in-java/) почему и как настроить идею, чтобы избавиться от `*`
Кстати, в IDEA есть отличное сочетание клавиш `Ctrl + Alt + O` - при нажатии сочетания в нужном классе автоматически оптимизируются импорты и удаляются ненужные

2022-11-01 10:19 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private String name;
Лучше добавлять пустую строку после каждой переменной, если над ней стоит аннотация - так становится проще визуально воспринимать код

2022-11-01 10:19 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +public class FilmControllerTest {
Молодец, что добавил тесты 👍

2022-11-01 10:19 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +            badDescription += "/";
Лучше использовать [StringBuilder](https://metanit.com/java/tutorial/7.3.php), он безопаснее и дешевле склеит строку в цикле, чем конкатенация

2022-11-01 10:19 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +        assertEquals(controller.getAll().size(), 0);
Тут и не должно ничего добавляться, потому что ты просто проходишься по всем фильмам и смотришь, пуста ли коллекция с фильмами.
Чтобы тест лучше соответствовал названию, фильмы нужно куда-то добавлять, а потом проверять, что мы получили ошибку

2022-11-01 10:19 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +        ArrayList<User> arr = new ArrayList<>(controller.getAll());
Лучше определять интерфейс, а создавать объект уже с определенно реализацией. Так программа станет более гибкой и не сломается, если вдруг изменится реализация

2022-11-01 10:19 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +        assertEquals(controller.getAll().size(), 0);
Здесь тоже не добавляются "некорректные" пользователи, а просто каждый раз проверяется, что коллекция пуста. Нужно поправить тест, по аналогии с FilmControllerTest

2022-11-01 10:19 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +        assertEquals(arr.get(0).getEmail(), email);
`arr.get(0)` - можно вынести в переменную, так код будет проще читать

2022-11-01 10:19 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +    @MethodSource("validUsers")
Параметризованные тесты, это очень удобно, молодец, что разобрался 🔥

2022-11-01 18:34 UTC, StRaiGT commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getReleaseDate().isBefore(LocalDate.of(1895, 12, 28))) {
Вынес в константу

2022-11-01 18:35 UTC, StRaiGT commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +import org.springframework.web.bind.annotation.*;
Спасибо!
Поправил.

2022-11-01 18:37 UTC, StRaiGT commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private String name;
Поправил

2022-11-01 18:49 UTC, StRaiGT commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +            badDescription += "/";
Поправил

2022-11-01 18:51 UTC, StRaiGT commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +        ArrayList<User> arr = new ArrayList<>(controller.getAll());
Изменил на интерфейс

2022-11-01 18:58 UTC, StRaiGT commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +        assertEquals(arr.get(0).getEmail(), email);
Вынес в константу

2022-11-01 19:26 UTC, StRaiGT commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +        assertEquals(controller.getAll().size(), 0);
Добавил потерянную логику для проверки объектов поступающих "изнутри", а не через HTTP

2022-11-01 19:26 UTC, StRaiGT commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +        assertEquals(controller.getAll().size(), 0);
Аналогично FilmControllerTest. Добавил потерянную логику для проверки объектов поступающих "изнутри", а не через HTTP

2022-11-02 10:54 UTC, AnastasiyaFomkina reviewed
Предлагаю вернуть валидацию, как было, чтобы не дублировать проверки, а параметризованные тесты, пока убрать

2022-11-02 10:54 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +        assertEquals(controller.getAll().size(), 0);
Лучше, наверное, просто удалить тест, так как сейчас получилось дублирование проверки. Все данные будут приходить по апи, поэтому внутреннюю валидацию добавлять ненужно. В будущем будет информация про тесты спинга, и с помощью них можно будет как раз попробовать реализовать данный кейс

2022-11-02 10:54 UTC, afomkina commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +        assertEquals(controller.getAll().size(), 0);
И здесь тоже

2022-11-02 20:50 UTC, StRaiGT commented
Убрал дублирующую внутреннюю валидацию. Убрал лишние и переделал параметрические тесты. 
Оставил только то, что требуются для валидации по апи.

2022-11-03 06:01 UTC, AnastasiyaFomkina approved these changes

2022-11-03 07:25 UTC, merged