Develop
StRaiGT/java-filmorate pull request #13
Opened 2022-12-27 13:25 UTC by StRaiGT

sprint 12

2022-12-28 10:06 UTC, AnastasiyaFomkina requested changes
Привет! Вы проделали большую работу, молодцы 👍 У вас получился отличный проект и появились навыки работы в команде.

2022-12-28 10:06 UTC, afomkina commented on README.md
> +![](scheme.png)
Добавьте, пожалуйста, в описание проекта список сделанных задач

2022-12-28 10:06 UTC, afomkina commented on postman/sprint_12_add-director.json
> +{
Супер, что приложили все коллекции для постмана, очень удобно, что их можно быстро добавить себе и протестировать проект 🔥

2022-12-28 10:06 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/model/Director.java
> +    public int compareTo(Director o) {
Лучше именовать параметры осмысленно, однобуквенные названия делают код менее читаемым.
Предлагаю поправить во всех классах с изменениями

2022-12-28 10:06 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DbDirectorStorage.java
> +        } catch (EmptyResultDataAccessException e) {
Лучше переименовать
```suggestion
        } catch (EmptyResultDataAccessException exception) {
```

2022-12-28 10:06 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/DbFilmStorage.java
> +    private final DbDirectorStorage dbDirectorStorage;
Лучше обозначать интерфейс: 
```suggestion
    private final DirectorStorage dbDirectorStorage;
```
Так программа будет более гибкой, и если изменится реализация, ничего не сломается
Предлагаю поправить еще и 31 строку

2022-12-28 10:06 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    public Review(int reviewId, String content, String isPositive, int userId, int filmId, int useful) {
_Опционально_
Можно заменить на [@AllArgsConstructor](https://habr.com/ru/company/piter/blog/676394/#:~:text=%D0%BA%D0%BE%D0%B3%D0%B4%D0%B0%20%D0%BA%D0%BB%D0%B0%D1%81%D1%81%20%D0%B0%D0%BD%D0%BD%D0%BE%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD-,%40AllArgsConstructor,-%2C%20%D0%B1%D1%83%D0%B4%D0%B5%D1%82%20%D1%81%D0%B3%D0%B5%D0%BD%D0%B5%D1%80%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%20%D0%BA%D0%BE%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%82%D0%BE%D1%80). Так код немного сократится и будет выглядеть чище

2022-12-28 10:06 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +        if (isPositive == null) {
_Опционально_
Можно заменить на аннотацию `@NotNull`

2022-12-28 10:06 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +        } else this.isPositive = !isPositive.equals("false");
Лучше все блоки кода после какого-либо условия заключать в фигурные скобки - `{}`, даже однострочные. Так код будет выглядеть более структурированно и читать его будет проще

2022-12-28 10:06 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +@FieldDefaults(level = AccessLevel.PRIVATE)
👍

2022-12-28 10:06 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewsController.java
> +    public Optional<Review> createReview(@RequestBody Review review) {
Лучше доставать объект из `Optional`, прежде чем возвращать результат. Это можно сделать на уровне сервиса

2022-12-28 10:06 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +    private void validateOfReview(Review review) {
Лучше реализовать валидацию с помощью [аннотаций](https://www.baeldung.com/javax-validation#:~:text=4.%20Using%20Validation%20Annotations) на уровне модели

2022-12-28 10:06 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        feedService.add(result.get().getReviewId(), result.get().getUserId(), REVIEW, ADD);
Прежде, чем доставать объект из Optional `result.get()`. Нужно проверить, что он там существует. Это можно сделать с помощью обычного условия и проверки на `isPresent()` или другим удобным способом. 
В коммерческой разработке чаще всего используется метод `.orElseThrow()`, так как сразу позволяет получить объект из `Optional` или выкинуть ошибку, если в нем ничего не окажется.
Вот хорошая [статья про Optional](https://habr.com/ru/post/346782/)

2022-12-28 10:06 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        feedService.add(review.getReviewId(), reviewStorage.getReviewById(review.getReviewId()).get().getUserId(), REVIEW, UPDATE);
Длинная строка: лучше перенести несколько параметров на следующую строку, чтобы было проще читать код

2022-12-28 10:06 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/controller/DirectorControllerTest.java
> +public class DirectorControllerTest {
Клево, что добавили тесты 👍

2022-12-28 10:06 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +        List<User> arr = userController.getAllUsers();
Лучше именовать переменные осмысленно. Поправь, пожалуйста, во всем тесте

2022-12-28 11:30 UTC, StRaiGT commented on README.md
> +![](scheme.png)
добавил

2022-12-28 11:30 UTC, StRaiGT commented on src/main/java/ru/yandex/practicum/filmorate/model/Director.java
> +    public int compareTo(Director o) {
поправил тут и в модели Genre

2022-12-28 11:30 UTC, StRaiGT commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DbDirectorStorage.java
> +        } catch (EmptyResultDataAccessException e) {
Поправил

2022-12-28 11:31 UTC, StRaiGT commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/DbFilmStorage.java
> +    private final DbDirectorStorage dbDirectorStorage;
Исправил оба

2022-12-28 11:31 UTC, StRaiGT commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +        if (isPositive == null) {
в текущих тестах нет такой проверки

2022-12-28 11:32 UTC, StRaiGT commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +        } else this.isPositive = !isPositive.equals("false");
убрали ручной конструктор

2022-12-28 11:33 UTC, StRaiGT commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    public Review(int reviewId, String content, String isPositive, int userId, int filmId, int useful) {
заменили ручной конструктор на аннотацию @AllArgsConstructor

2022-12-28 11:49 UTC, StRaiGT commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewsController.java
> +    public Optional<Review> createReview(@RequestBody Review review) {
сделано

2022-12-28 11:50 UTC, StRaiGT commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +    private void validateOfReview(Review review) {
сделано

2022-12-28 12:47 UTC, StRaiGT commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        feedService.add(review.getReviewId(), reviewStorage.getReviewById(review.getReviewId()).get().getUserId(), REVIEW, UPDATE);
done

2022-12-28 13:30 UTC, StRaiGT commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        feedService.add(result.get().getReviewId(), result.get().getUserId(), REVIEW, ADD);
Поправил

2022-12-28 13:39 UTC, StRaiGT commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +        List<User> arr = userController.getAllUsers();
Исправил

2022-12-28 15:59 UTC, AnastasiyaFomkina requested changes
Нужно переработать функционал рекомендаций таким образом, чтобы в запросе в базу не было множественных вложенных подзапросов. За подсказкой можно обратиться к наставнику

2022-12-28 15:59 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/DbFilmStorage.java
> +                "likes.film_id IN (SELECT likes.film_id FROM likes WHERE likes.user_id = ?) " +
Слишком много вложенных запросов. Нужно упростить запрос в базу

2022-12-28 19:28 UTC, StRaiGT commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/DbFilmStorage.java
> +                "likes.film_id IN (SELECT likes.film_id FROM likes WHERE likes.user_id = ?) " +
разбил запрос на два логических запроса поменьше

2022-12-29 14:02 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +                reviewStorage.getReviewById(review.getReviewId()).get().getUserId(), REVIEW, UPDATE);
Нужно проверить, что `Optional` не пуст, прежде, чем получать значение

2022-12-29 14:02 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        Optional<Review> optionalReview = reviewStorage.getReviewById(id);
Можно сразу проверять, что `Optional` не пуст и вытаскивать из него значение

2022-12-29 14:02 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            throw new ValidationException(String.format("Некорректные параметры сортировки в запросе."));
_Опционально_
Можно убрать `String.format`, так как тут строку форматировать никак не нужно

2022-12-29 14:02 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        List<Film> films;
_Опционально_
Можно отказаться от переменной, если с блоках условий сразу возвращать полученное значение:
`return filmStorage.getFilmsByDirectorSortLikes(directorId);`

2022-12-29 14:02 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        query = "%" + query.toLowerCase() + "%";
`Опционально`
Лучше объединять через String.format или [StringBuilder](https://metanit.com/java/tutorial/7.3.php)

2022-12-29 14:24 UTC, StRaiGT commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +                reviewStorage.getReviewById(review.getReviewId()).get().getUserId(), REVIEW, UPDATE);
Заменил на уже написанный метод getReviewById класса ReviewService.

2022-12-29 14:26 UTC, StRaiGT commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        Optional<Review> optionalReview = reviewStorage.getReviewById(id);
Заменил на уже написанный метод getReviewById класса ReviewService.

2022-12-29 14:27 UTC, StRaiGT commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            throw new ValidationException(String.format("Некорректные параметры сортировки в запросе."));
Убрал лишнее

2022-12-29 14:28 UTC, StRaiGT commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        List<Film> films;
Согласен, поправил

2022-12-29 14:47 UTC, StRaiGT commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        query = "%" + query.toLowerCase() + "%";
переделал на String.format

2022-12-29 15:47 UTC, AnastasiyaFomkina approved these changes
Поздравляю с успешным завершением группового проекта и наступающими праздниками 🎄

2022-12-29 15:58 UTC, Abrielz1 approved these changes

2022-12-29 16:05 UTC, merged