Sprint 10
StRaiGT/java-filmorate pull request #2
Opened 2022-11-09 19:41 UTC by StRaiGT

2022-11-10 09:26 UTC, AnastasiyaFomkina requested changes

2022-11-10 09:26 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @Autowired
_Опционально_
Так как мы используем lombok в приложении, проще будет доверить инжект полей ему:
https://www.baeldung.com/spring-injection-lombok

2022-11-10 09:26 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    public ErrorResponse handleValidation(final RuntimeException e) {
Лучше не использовать однобуквенные названия переменных

2022-11-10 09:26 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    public ErrorResponse handleThrowable(final Throwable e) {
Предлагаю логировать мессадж ошибки, чтобы в логах можно было отследить, что пошло не так

2022-11-10 09:26 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private final Set<Integer> friends = new TreeSet<>();
Лучше использовать [HashSet](https://developer.alexanderklimov.ru/android/java/set.php), `TreeSet` здесь будет лишним, так как не нужно поддерживать явный порядок друзей

2022-11-10 09:26 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                .map(u -> userStorage.getUser(u))
Можно сократить:
```suggestion
                .map(userStorage::getUser)
```

2022-11-10 09:26 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                .map(u -> userStorage.getUser(u))
```suggestion
                .map(userStorage::getUser)
```

2022-11-10 09:26 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/model/ErrorResponse.java
> +    public String getError() {
Пока нигде не используется, лучше удалить, чтобы не загрязнять код

2022-11-10 09:26 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +        assertEquals("Дата релиза фильма не может быть раньше " + filmService.FIRST_FILM_RELEASE_DATE,
К статичным полям можно получать доступ по названию класса:
```suggestion
        assertEquals("Дата релиза фильма не может быть раньше " + FilmService.FIRST_FILM_RELEASE_DATE,
```

2022-11-10 09:26 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    private static FilmStorage filmStorage;
`static` для полей лишний, так как нам не нужно получать доступ к этим полям вне класса `FilmControllerTest`

2022-11-10 13:13 UTC, StRaiGT commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @Autowired
Почитал, разобрался с генерацией конструктора через аннотации lombok.
Пока решил не менять код.

2022-11-10 13:33 UTC, StRaiGT commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    public ErrorResponse handleValidation(final RuntimeException e) {
Переименовал

2022-11-10 13:35 UTC, StRaiGT commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    public ErrorResponse handleThrowable(final Throwable e) {
Передал функционал логирования ошибок отовсюду в ErrorHandler

2022-11-10 13:38 UTC, StRaiGT commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private final Set<Integer> friends = new TreeSet<>();
Done

2022-11-10 13:40 UTC, StRaiGT commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                .map(u -> userStorage.getUser(u))
Хорошая идея, спасибо!

2022-11-10 13:40 UTC, StRaiGT commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                .map(u -> userStorage.getUser(u))
Тут тоже.

2022-11-10 13:49 UTC, StRaiGT commented on src/main/java/ru/yandex/practicum/filmorate/model/ErrorResponse.java
> +    public String getError() {
Если удалить этот метод, то часть тестов выпадает в ошибку и возвращает ошибку 
WARN 888 --- [nio-8080-exec-3] .m.m.a.ExceptionHandlerExceptionResolver : Failure in @ExceptionHandler ru.yandex.practicum.filmorate.controller.ErrorHandler#handleThrowable(Throwable)
со статусом 500
Тут либо самому писать, либо генерировать через lombok.

2022-11-10 13:53 UTC, StRaiGT commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +        assertEquals("Дата релиза фильма не может быть раньше " + filmService.FIRST_FILM_RELEASE_DATE,
Done

2022-11-10 13:53 UTC, StRaiGT commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    private static FilmStorage filmStorage;
Сделал по инерции после стримов. Поправил.

2022-11-10 16:36 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @Autowired
Окей, молодец, что разобрался 👍

2022-11-10 16:41 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/model/ErrorResponse.java
> +    public String getError() {
Да, у нас коварные тесты 😁
Давай попробуем добавить аннотацию `@Getter `, чтобы пока сильно в глаза не бросалось (тогда поле error нужно будет сделать final), или оставим, как было, если тесты снова проходить не будет

2022-11-10 16:45 UTC, AnastasiyaFomkina reviewed
Оставила несколько комментариев к предыдущим и один новый небольшой комментарий 😁

2022-11-10 16:45 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    private FilmStorage filmStorage;
Поля filmStorage и filmService не используются явно в данном классе, можно их убрать в метод инициализации `createController`

2022-11-10 17:40 UTC, StRaiGT commented on src/main/java/ru/yandex/practicum/filmorate/model/ErrorResponse.java
> +    public String getError() {
Так поле Error уже final и @Getter добавил...

2022-11-10 17:45 UTC, StRaiGT commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    private FilmStorage filmStorage;
Спрятал поля

2022-11-11 06:04 UTC, AnastasiyaFomkina approved these changes

2022-11-11 06:46 UTC, merged