add-database
StRaiGT/java-filmorate pull request #3
Opened 2022-11-30 15:02 UTC by StRaiGT

add scheme and update readme

2022-12-01 08:31 UTC, KukushkinIgorA commented
1) Optional. В табличках пересечений можно сделать искусcтвеный Primary Key
2) Optional. В таблицы жанра и рейтинга можно добавить поле Description, где можно хранить описание жанра/рейтинга

2022-12-11 17:48 UTC, AnastasiyaFomkina requested changes
Отличная работа - молодец 👍

2022-12-11 17:48 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/DbFilmStorage.java
> +                        PreparedStatement ps = connection.prepareStatement(sqlQuery, new String[]{"FILM_ID"});
Лучше переименовать по code-style

2022-12-11 17:48 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/DbFilmStorage.java
> +    public static List<Film> makeFilms(ResultSet resultSet) throws SQLException {
Метод лучше сделать приватным, так как используется только в данном классе

2022-12-11 17:48 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/DbGenreStorage.java
> +    public static Genre makeGenre(ResultSet resultSet, int rowNum) throws SQLException {
Метод лучше сделать приватным, так как используется только в данном классе

2022-12-11 17:48 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/mpa/DbMpaStorage.java
> +    public static Mpa makeMpa(ResultSet resultSet, int rowNum) throws SQLException {
Метод лучше сделать приватным, так как используется только в данном классе

2022-12-11 17:48 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/DbUserStorage.java
> +    public static User makeUser(ResultSet resultSet, int rowNum) throws SQLException {
Метод лучше сделать приватным, так как используется только в данном классе

2022-12-11 17:48 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +    @Autowired
_Опционально_
Предлагаю использовать [@RequiredArgsConstructor](https://www.baeldung.com/spring-injection-lombok) от lombok. Он поможет не только избавиться от однотипного кода, но и его сократить

2022-12-11 19:10 UTC, StRaiGT commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/DbFilmStorage.java
> +                        PreparedStatement ps = connection.prepareStatement(sqlQuery, new String[]{"FILM_ID"});
done

2022-12-11 19:16 UTC, StRaiGT commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/DbFilmStorage.java
> +    public static List<Film> makeFilms(ResultSet resultSet) throws SQLException {
Остатки предыдущего варианта, который  предполагал собирать объект за три SQL-запроса.
Поправил.

2022-12-11 19:16 UTC, StRaiGT commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/DbGenreStorage.java
> +    public static Genre makeGenre(ResultSet resultSet, int rowNum) throws SQLException {
done

2022-12-11 19:16 UTC, StRaiGT commented on src/main/java/ru/yandex/practicum/filmorate/storage/mpa/DbMpaStorage.java
> +    public static Mpa makeMpa(ResultSet resultSet, int rowNum) throws SQLException {
done

2022-12-11 19:16 UTC, StRaiGT commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/DbUserStorage.java
> +    public static User makeUser(ResultSet resultSet, int rowNum) throws SQLException {
done

2022-12-11 19:23 UTC, StRaiGT commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +    @Autowired
Ок, убедила. Так код выглядит лаконичнее.
Поправил.

2022-12-12 12:44 UTC, AnastasiyaFomkina approved these changes

2022-12-12 12:45 UTC, afomkina approved these changes

2022-12-12 12:55 UTC, merged